name: Spark Dotnet Databricks

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    concurrency:
      group: ${{ github.ref }}  # Groups all runs of this workflow using the branch name
      cancel-in-progress: true  # Automatically cancels any previous run of the workflow that is not completed

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    
    environment: databricks
    
    env:
    
      Solution_Name: Spark.Connect.Dotnet                
      Test_Project_Path: src/test                
      DATABRICKS_URL: ${{ secrets.DATABRICKS_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CLUSTERID: ${{ secrets.DATABRICKS_CLUSTERID }}

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  # Specify your .NET Core version here
    
    - name: Print current directory
      run: pwd

    - name: Print current directory listing
      run: ls -a ./src

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    
    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build the project
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore
    
    - name: Test on Databricks
      working-directory: ./src/example/databricks_example
      run: dotnet run

    
